### ISSUE TITLE
[FR] Contacts grouping for different kinds of emergencies. 

### ISSUE THREAD

**Issue by HarryHeights** [tacticalDevC/PanicTrigger#10]
I had to open a new issue for this feature request. I feel we've talked so much on the other one. 

The idea is; I'd love to be able to group contacts for different kinds of emergency situations. You know, currently on the app, once I hit the trigger button, it sends messages to all the contacts I have configured on the app. But, there are emergency cases where I would need to contact only a selected group of people. 

For example, there is a robbery attack; The best person to contact would be a security agent. (I'm fortunate to have some of them as friends). In that case, they will be my first point of contact. 
There could be a fire emergency; Best person to contact would be someone in the fire service. 

So I'll stop here on the list of emergency situations I could be in, but, I'm sure you already got my point. 

I would configure contacts in groups like this;

- Fire emergency
- Accident
- Robbery
- General, etc. 

Implementing the contact grouping might not be so hard to do (it might be though; I'm sorry, I'm not a developer so I don't know). The real challenge is how to trigger the emergency alert to my defined contacts quickly. Because the whole point of the app is to be able to reach out to someone quickly. I initially imagined the user having to go to settings to select which contact group he/she wishes to contact. But, that is too long a process, especially in cases where the touch of my phone is limited. 

#### Here's my idea to solve the issue. 

Instead of having one main trigger button, have plenty of them as the user defines it. On the main screen, when a user creates a contact group, it creates a trigger button of that group on the main screen. 

So if I create 3 contact groups; I would have 3 trigger buttons on the app. 

Here, lemme show you a pictorial example;

![Screenshot_2019-03-21-10-37-50-680_at tacticaldevc panictrigger](https://user-images.githubusercontent.com/40593824/54744091-57ca6300-4bc6-11e9-8fff-4ea8d18d8c18.png)

So there you have it, 3 different triggers for different situations. I left the original trigger button. When that button is tapped, all my contact groups would be notified of an emergency. 

Another thing that would be done is that; I will have to create an emergency text for each contact group. For example, for fire emergencies, I could create an emergency text like; ` A building is on fire, you need to get here right now!!!`.  Now, this is where my previous suggestion about sending a resolved location would come in handy. 

This suggestion might affect UI. For example, if I create 10 contact groups, it would mean 10 triggers on the main page. It is bound to look messy. My idea would be to limit emergency groups to a maximum of 4 or 5.  

Lemme know what you think about this.

**Comment by tacticalDevC** [comment]
This is a very nice suggestion. I already thought of it having kind of a text field to tell your contacts what is going on but this replaces my initial idea. However I labeled this with "future" because I want to implement the more "core" features first. I hope you understand :)

**Comment by HarryHeights** [comment]
Sure. I understand

**Comment by tacticalDevC** [comment]
Closing this as this feature is implemented. Opening a new issue for the custom text...
