### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by tacticalDevC** [tacticalDevC/PanicTrigger#14]
As mentioned by @HarryHeights there is no privacy statement for PanicTrigger.

**Comment by HarryHeights** [comment]
Working on this at the moment.

**Comment by HarryHeights** [comment]
Hello! Good day. I'm almost done with the policy statement. I wanted to inquire though; Do you receive crash reports when the app crashes? Because that's a form of data collection. And aside from OSMdroid, do you use any other third party service?

**Comment by tacticalDevC** [comment]
Oh I'm sorry I didn't see the email regarding you message.
I already merged your PR.
Crash reports can be send in a future release. Aside from OSMdroid there is no other library in use.
Closing this issue because of the merged PR.
Thank your again for your work :)
