### ISSUE TITLE
Contributers Guide

### ISSUE THREAD

**Issue by tacticalDevC** [tacticalDevC/PanicTrigger#15]
As mention by @HarryHeights there is no Contributers Guide for PanicTrigger. This is the thread for this issue

**Comment by HarryHeights** [comment]
I will take some time to work on this one.

**Comment by tacticalDevC** [comment]
That's no problem. Take your time :) it isn't urgent

**Comment by tacticalDevC** [comment]
Closing this because the work is done. Thanks Harry
