### ISSUE TITLE
[BUG] Unexpected stop

### ISSUE THREAD

**Issue by GrigoreBurlacu** [tacticalDevC/PanicTrigger#2]
**Describe the bug**
Aplication stops when pressing panic Button having location disabled.

**To Reproduce**
1. Disable location if enabled
2. Open the application
3. Press the panic button

**Expected behavior**
Application must check if location is disabled, try to enable, if fails, send alarm message without coordinates.

**Screenshots**
Not needed.

**Smartphone (please complete the following information):**
 - Device: Motorola One
 - OS:  Android 9
 - Application version 0.4-2

**Additional context**

**Comment by tacticalDevC** [comment]
Hey friend :)

Thank you very much for your feedback! I'm very glad that you use my application ^^

This problem will be fixed with the next release. The next release will occur approximately in the next week because of too little time for my projects... Anyway thank you very much :)

**Comment by tacticalDevC** [comment]
Hmmm looks like you can only enable location services programmatically if you have the permission to write to the secure settings or have Google APIs implemented. I won't use Google APIs. Since this is out of scope please open another issue if you want to have the ability to automatically enable location services.

Anyway as of the newest commit (see above) your issue should be fixed. Thanks for making me aware of this :)

**Comment by GrigoreBurlacu** [comment]
I don't like Google API too, it's too invasive. I think I can enable the permission to write to the secure settings, but for many users it can be too complicated. Any way, your application is a good idea and is good without gps also. They are many cases when location is impossible to get - between hills, inside of a building, in the forest, In this cases  it's enough to alert without location. Thank you very much.

**Comment by tacticalDevC** [comment]
Thank you for your feedback :)
This application has multiple fallbacks. First the network location is acquired. If this doesn't work the same is tried with GPS which should work on most places. Last but least the last known location will be taken. If everything fails the application sends the SMS without any location data thanks to your issue.

Thanks for using and contributing to my application :)
You are welcome!
