### ISSUE TITLE
[BUG-] the application  crashes when i double click on home screen

### ISSUE THREAD

**Issue by 44asad** [tacticalDevC/PanicTrigger#22]
### Expected behavior

I expected that the application should not be crash when i click on the trigger home screen

### Actual behavior

After configure the application when i click on the trigher home screen the application is crash you can see in bug video properly

### How to reproduce

* Download and open the application

* click on home screen doubel cilick

* Note the Bug

### Information
Browser/App version: 0.4-2

Operating system: 6.0.1
### Recording Of The Bug

https://youtu.be/Y-zqlhtlmrM

**Comment by tacticalDevC** [comment]
Hello friend!
Thank you for reaching out to me. Could you please provide me a stacktrace? You can either do that by using an application (requires root privileges) or by using Android Studio.

**Comment by 44asad** [comment]
@tacticalDevC ok sir

**Comment by 44asad** [comment]
logcat
04-30 07:34:39.749 20113 20113 E AndroidRuntime: FATAL EXCEPTION: main

04-30 07:34:39.749 20113 20113 E AndroidRuntime: Process: at.tacticaldevc.panictrigger, PID: 20113

04-30 07:34:39.749 20113 20113 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.view.View.performClick(View.java:5698)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:10908)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22565)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7231)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	... 10 more

04-30 07:34:39.749 20113 20113 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid destinationAddress

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:343)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at at.tacticaldevc.panictrigger.TriggerActivity.sendOutPanic(TriggerActivity.java:153)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at at.tacticaldevc.panictrigger.TriggerActivity.getCurrentLocationAndPanic(TriggerActivity.java:179)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	at at.tacticaldevc.panictrigger.TriggerActivity.onClick(TriggerActivity.java:133)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: 	... 12 more

**Comment by 44asad** [comment]
<pre><code>04-30 07:34:39.749 20113 20113 E AndroidRuntime: FATAL EXCEPTION: main

04-30 07:34:39.749 20113 20113 E AndroidRuntime: Process: at.tacticaldevc.panictrigger, PID: 20113

04-30 07:34:39.749 20113 20113 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.view.View.performClick(View.java:5698)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.widget.TextView.performClick(TextView.java:10908)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.view.View$PerformClick.run(View.java:22565)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:739)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:95)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.os.Looper.loop(Looper.java:158)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7231)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: ... 10 more

04-30 07:34:39.749 20113 20113 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid destinationAddress

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:343)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at at.tacticaldevc.panictrigger.TriggerActivity.sendOutPanic(TriggerActivity.java:153)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at at.tacticaldevc.panictrigger.TriggerActivity.getCurrentLocationAndPanic(TriggerActivity.java:179)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: at at.tacticaldevc.panictrigger.TriggerActivity.onClick(TriggerActivity.java:133)

04-30 07:34:39.749 20113 20113 E AndroidRuntime: ... 12 more</code></pre>

**Comment by tacticalDevC** [comment]
> 04-30 07:34:39.749 20113 20113 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid destinationAddress

According to the logcat the number to which you send the panic message to is invalid. Please check the number. It may contain a + or a space but I think there shouldn't be any other character.

Additionally I will add a check if the added phone number is valid.

Please confirm that this was the issue.

**Comment by 44asad** [comment]
i did not added number yet.This happening without adding number

**Comment by 44asad** [comment]
### logcat
<pre><code>05-01 20:39:13.356 29329 29329 E AndroidRuntime: FATAL EXCEPTION: main
05-01 20:39:13.356 29329 29329 E AndroidRuntime: Process: at.tacticaldevc.panictrigger, PID: 29329
05-01 20:39:13.356 29329 29329 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.view.View.performClick(View.java:5698)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.widget.TextView.performClick(TextView.java:10908)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.view.View$PerformClick.run(View.java:22565)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-01 20:39:13.356 29329 29329 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   ... 10 more
05-01 20:39:13.356 29329 29329 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid destinationAddress
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:343)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at at.tacticaldevc.panictrigger.TriggerActivity.sendOutPanic(TriggerActivity.java:153)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at at.tacticaldevc.panictrigger.TriggerActivity.getCurrentLocationAndPanic(TriggerActivity.java:179)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   at at.tacticaldevc.panictrigger.TriggerActivity.onClick(TriggerActivity.java:133)
05-01 20:39:13.356 29329 29329 E AndroidRuntime:   ... 12 more</code></pre>

**Comment by tacticalDevC** [comment]
Is this issue solved from your side now?

**Comment by 44asad** [comment]
ok sir, thanks you

**Comment by 44asad** [comment]
pleased  closed  this issues.
