### ISSUE TITLE
Apk version.

### ISSUE THREAD

**Issue by HarryHeights** [tacticalDevC/PanicTrigger#28]
It's good to see a new release is out. I was hoping to get my hands on the apk file.

**Comment by tacticalDevC** [comment]
I'm really sorry that I didn't give an APK file to you before release if that's what you wanted. I will create a Telegram group for general discussion and pre-releases.

**Comment by HarryHeights** [comment]
The telegram group is a great idea. And you don't have to feel sorry about the apk file. I just want to get my hands on it.

**Comment by tacticalDevC** [comment]
Closing this issue as it is resolved and the Telegram group is up and running
