### ISSUE TITLE
Unable to install update.

### ISSUE THREAD

**Issue by HarryHeights** [tacticalDevC/PanicTrigger#29]
**Describe the bug**
The latest release was finally updated on F-Droid, but the app won't install. 

**Test Environment:**
 - Device: Xiaomi Redmi Note 5 Pro
 - OS: Android 9.0
 - Application version: PanicTrigger v0.5

**Comment by tacticalDevC** [comment]
Hey im very sorry that you couldn't install the update.
Had you installed a version from GitHub instead of from F-Droid?

**Comment by tacticalDevC** [comment]
Hey Harry is your issue resolved?

**Comment by HarryHeights** [comment]
Yes it has been resolved. I found a way to install it. It's been a long time man.

**Comment by tacticalDevC** [comment]
Yeah I know. Gonna start development again. Had to have some more free time. Closing this issue now.
